
version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - ./docker/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    ports:
      - "9080:9080"
  